/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisisnum;

import static analisisnum.AnalisisNum.distancia;
import static analisisnum.AnalisisNum.puntosY;
import static java.lang.Math.sqrt;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFrame;
import groovy.lang.GroovyClassLoader;
import groovy.lang.GroovyShell;


/**
 *
 * @author alejandro
 */
public class GUI_Analisis extends JFrame {

    /**
     * Creates new form GUI_Analisis
     */
    public GUI_Analisis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RectangulosRadioButton = new javax.swing.JRadioButton();
        TrapeciosRadioButton = new javax.swing.JRadioButton();
        SemicirculosRadioButton = new javax.swing.JRadioButton();
        ResolucionSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SinRadioButton = new javax.swing.JRadioButton();
        XmasUnoRadioButton = new javax.swing.JRadioButton();
        xALa2RadioButton = new javax.swing.JRadioButton();
        XConstanteRadioButton = new javax.swing.JRadioButton();
        IntegrarButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AreaTextField = new javax.swing.JLabel();
        ResultadoDeAreaTextField = new javax.swing.JTextField();
        ErrorTruncamientoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        aTextField = new javax.swing.JTextField();
        bTextField = new javax.swing.JTextField();
        jButtonRaiz = new javax.swing.JButton();
        jButtonPotenciacuadrado = new javax.swing.JButton();
        jButtonSen = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIntegrar = new javax.swing.JTextArea();
        jButtonPotenciacubo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Maquina Integradora!");

        RectangulosRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RectangulosRadioButton.setSelected(true);
        RectangulosRadioButton.setText("Rectangulos");
        RectangulosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectangulosRadioButtonActionPerformed(evt);
            }
        });

        TrapeciosRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TrapeciosRadioButton.setText("Trapecios");
        TrapeciosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapeciosRadioButtonActionPerformed(evt);
            }
        });

        SemicirculosRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SemicirculosRadioButton.setText("Semicirculos");
        SemicirculosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemicirculosRadioButtonActionPerformed(evt);
            }
        });

        ResolucionSlider.setMajorTickSpacing(100);
        ResolucionSlider.setMaximum(6000);
        ResolucionSlider.setMinimum(10);
        ResolucionSlider.setMinorTickSpacing(2);
        ResolucionSlider.setPaintLabels(true);
        ResolucionSlider.setPaintTicks(true);
        ResolucionSlider.setSnapToTicks(true);
        ResolucionSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ResolucionSliderStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Area de integracion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Resolucion:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Funcion de particion:");

        SinRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SinRadioButton.setText("sin (x) + 1, x > 0");
        SinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinRadioButtonActionPerformed(evt);
            }
        });

        XmasUnoRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        XmasUnoRadioButton.setText("x+1, x > 0");
        XmasUnoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XmasUnoRadioButtonActionPerformed(evt);
            }
        });

        xALa2RadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xALa2RadioButton.setText("x^2, x > 0");
        xALa2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xALa2RadioButtonActionPerformed(evt);
            }
        });

        XConstanteRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        XConstanteRadioButton.setSelected(true);
        XConstanteRadioButton.setText("x Constante");
        XConstanteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XConstanteRadioButtonActionPerformed(evt);
            }
        });

        IntegrarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IntegrarButton.setText("Integrar!");
        IntegrarButton.setToolTipText("Se integrara con una precision de 7 decimales");
        IntegrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegrarButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Grafica de la funcion a integrar:");

        AreaTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AreaTextField.setText("Resultado de area:");

        ResultadoDeAreaTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResultadoDeAreaTextField.setText("0");
        ResultadoDeAreaTextField.setToolTipText("");

        ErrorTruncamientoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ErrorTruncamientoTextField.setText("0");
        ErrorTruncamientoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorTruncamientoTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Error de truncamiento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Funcion a integrar:");

        ResLabel.setText("res: 10");

        jLabel8.setText("Limite inferior (a):");

        jLabel9.setText("Limite superior (b):");

        aTextField.setText("0");
        aTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTextFieldActionPerformed(evt);
            }
        });

        bTextField.setText("10");

        jButtonRaiz.setText("√");
        jButtonRaiz.setToolTipText("");
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });

        jButtonPotenciacuadrado.setText("^2");
        jButtonPotenciacuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciacuadradoActionPerformed(evt);
            }
        });

        jButtonSen.setText("sen()");
        jButtonSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSenActionPerformed(evt);
            }
        });

        jButtonCos.setText("cos()");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });

        jButtonTan.setText("tan()");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });

        jTextAreaIntegrar.setColumns(20);
        jTextAreaIntegrar.setRows(5);
        jScrollPane1.setViewportView(jTextAreaIntegrar);

        jButtonPotenciacubo.setText("^3");
        jButtonPotenciacubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciacuboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ResolucionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RectangulosRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrapeciosRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SemicirculosRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AreaTextField)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ErrorTruncamientoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ResultadoDeAreaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(IntegrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xALa2RadioButton)
                            .addComponent(XmasUnoRadioButton)
                            .addComponent(SinRadioButton)
                            .addComponent(XConstanteRadioButton)
                            .addComponent(ResLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPotenciacubo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPotenciacuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPotenciacuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jButtonPotenciacubo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(RectangulosRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrapeciosRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SemicirculosRadioButton)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AreaTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultadoDeAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ErrorTruncamientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ResolucionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResLabel)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(XConstanteRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SinRadioButton))
                    .addComponent(IntegrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XmasUnoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xALa2RadioButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void RectangulosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectangulosRadioButtonActionPerformed
        // TODO add your handling code here:
        RectangulosRadioButton.setSelected(true);
        TrapeciosRadioButton.setSelected(false);
        SemicirculosRadioButton.setSelected(false);
    }//GEN-LAST:event_RectangulosRadioButtonActionPerformed

    private void TrapeciosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapeciosRadioButtonActionPerformed
        // TODO add your handling code here:
        RectangulosRadioButton.setSelected(false);
        TrapeciosRadioButton.setSelected(true);
        SemicirculosRadioButton.setSelected(false);
    }//GEN-LAST:event_TrapeciosRadioButtonActionPerformed

    private void XConstanteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XConstanteRadioButtonActionPerformed
        // TODO add your handling code here:
        XConstanteRadioButton.setSelected(true);
        SinRadioButton.setSelected(false);
        XmasUnoRadioButton.setSelected(false);
        xALa2RadioButton.setSelected(false);
    }//GEN-LAST:event_XConstanteRadioButtonActionPerformed

    private void ErrorTruncamientoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorTruncamientoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorTruncamientoTextFieldActionPerformed

    private void SemicirculosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemicirculosRadioButtonActionPerformed
        // TODO add your handling code here:
        RectangulosRadioButton.setSelected(false);
        TrapeciosRadioButton.setSelected(false);
        SemicirculosRadioButton.setSelected(true);
    }//GEN-LAST:event_SemicirculosRadioButtonActionPerformed

    private void SinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinRadioButtonActionPerformed
        // TODO add your handling code here:
        XConstanteRadioButton.setSelected(false);
        SinRadioButton.setSelected(true);
        XmasUnoRadioButton.setSelected(false);
        xALa2RadioButton.setSelected(false);
    }//GEN-LAST:event_SinRadioButtonActionPerformed

    private void XmasUnoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XmasUnoRadioButtonActionPerformed
        // TODO add your handling code here:
        XConstanteRadioButton.setSelected(false);
        SinRadioButton.setSelected(false);
        XmasUnoRadioButton.setSelected(true);
        xALa2RadioButton.setSelected(false);
    }//GEN-LAST:event_XmasUnoRadioButtonActionPerformed

    private void IntegrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegrarButtonActionPerformed
        // TODO add your handling code here:
        List<Float> listX = new ArrayList<>();
        List<Float> listY = new ArrayList<>();
        float cantidadPuntos = ResolucionSlider.getValue();;
        float a = Float.parseFloat(aTextField.getText());
        float b = Float.parseFloat(bTextField.getText());
        String eq = jTextAreaIntegrar.getText();
        float t = (float) sqrt(4)+3+4;
        System.out.println(t);
        System.out.println(eq);
        listX = puntos(a, b,cantidadPuntos);
        if(XConstanteRadioButton.isSelected()){
            
        }
        System.out.println("-------------------------------------------------------------- ");
        if(SinRadioButton.isSelected()){
            listX = particionSin(listX, a, b);
        }
        System.out.println("-------------------------------------------------------------- ");
        if(XmasUnoRadioButton.isSelected()){        
            listX = xMasUno(listX, a, b);
        }
        System.out.println("-------------------------------------------------------------- ");
        if(xALa2RadioButton.isSelected()){        
            listX = xALa2(listX, a , b);
        }
        
                
        listY = puntosY(listX, eq);
        System.out.println("-------------------------------------------------------------- ");
        if(RectangulosRadioButton.isSelected()){
            System.out.println("Area rectangular: " + areaRectangular(a, b, listX, listY));
            ResultadoDeAreaTextField.setText(String.valueOf(areaRectangular(a, b, listX, listY)));
        }
        System.out.println("-------------------------------------------------------------- ");
        if(TrapeciosRadioButton.isSelected()){
            System.out.println("Area trapezoidal: " + areaTrapezoidal(a, b, listX, listY));
            ResultadoDeAreaTextField.setText(String.valueOf(areaTrapezoidal(a, b, listX, listY)));
        }
        System.out.println("-------------------------------------------------------------- ");
        if(SemicirculosRadioButton.isSelected()){        
            System.out.println("Area semicircular: " + areaSemicircular(a, b, listX, listY));
            ResultadoDeAreaTextField.setText(String.valueOf(areaSemicircular(a, b, listX, listY)));
        }
        ErrorTruncamientoTextField.setText(String.valueOf(errorTruncamientoTrap(a, b, listX, listY, eq)));
      
        
    }//GEN-LAST:event_IntegrarButtonActionPerformed

    private void ResolucionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ResolucionSliderStateChanged
        // TODO add your handling code here:
                ResLabel.setText(String.valueOf(ResolucionSlider.getValue()));
         
    }//GEN-LAST:event_ResolucionSliderStateChanged

    private void aTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTextFieldActionPerformed

    private void xALa2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xALa2RadioButtonActionPerformed
        // TODO add your handling code here:
        XConstanteRadioButton.setSelected(false);
        SinRadioButton.setSelected(false);
        XmasUnoRadioButton.setSelected(false);
        xALa2RadioButton.setSelected(true);
    }//GEN-LAST:event_xALa2RadioButtonActionPerformed

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        // TODO add your handling code here:
        jTextAreaIntegrar.append("sqrt()");
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jButtonPotenciacuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciacuadradoActionPerformed
        // TODO add your handling code here:
        jTextAreaIntegrar.append("elevarcuadrado()");
    }//GEN-LAST:event_jButtonPotenciacuadradoActionPerformed

    private void jButtonSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSenActionPerformed
        jTextAreaIntegrar.append("sin()");
        
    }//GEN-LAST:event_jButtonSenActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        jTextAreaIntegrar.append("cos()");
      
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
       jTextAreaIntegrar.append("tan()");

    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButtonPotenciacuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciacuboActionPerformed
        // TODO add your handling code here:
        jTextAreaIntegrar.append("elevarcubo()");
    }//GEN-LAST:event_jButtonPotenciacuboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Analisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaTextField;
    private javax.swing.JTextField ErrorTruncamientoTextField;
    private javax.swing.JButton IntegrarButton;
    private javax.swing.JRadioButton RectangulosRadioButton;
    private javax.swing.JLabel ResLabel;
    private javax.swing.JSlider ResolucionSlider;
    private javax.swing.JTextField ResultadoDeAreaTextField;
    private javax.swing.JRadioButton SemicirculosRadioButton;
    private javax.swing.JRadioButton SinRadioButton;
    private javax.swing.JRadioButton TrapeciosRadioButton;
    private javax.swing.JRadioButton XConstanteRadioButton;
    private javax.swing.JRadioButton XmasUnoRadioButton;
    private javax.swing.JTextField aTextField;
    private javax.swing.JTextField bTextField;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonPotenciacuadrado;
    private javax.swing.JButton jButtonPotenciacubo;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonSen;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaIntegrar;
    private javax.swing.JRadioButton xALa2RadioButton;
    // End of variables declaration//GEN-END:variables

    
    public static float distancia( float a, float b){

        return Math.abs(b - a);
    }
    public static List<Float> puntos( float a, float b, float cantidadPuntos){
        
        List<Float> listA = new ArrayList<>();
        float n = distancia(a ,b);
        float n2 = n / cantidadPuntos;
        float n3 = n2;
        listA.add(a);
        
        for(int i = 0; i < cantidadPuntos; i++){
            listA.add(a + n2);
            n2 = n3 + n2;
        }
        return listA;
    }
    public static List<Float>  puntosY(List<Float> x, String equation){ //funcion modificada para que reciba strings
        List<Float> listY = new ArrayList<>();
        GroovyShell shell = new GroovyShell();
         double res;
        System.out.println("evaluando "+ equation);
        for(Float f : x){
            //System.out.println("x:       y:");
            //System.out.println(f + "   " + (float)Math.sin(f));
          shell.setVariable("x",f);
          shell.evaluate("" +                       //este pedazo define que hace cada expresion que se ponga en el input, si quieren agregar mas, tienen que definirlo aqui y asignarle la accion que debe hacer
            "cos = {double x -> Math.cos(x)}\n" +   // define cos
            "sin = {double x -> Math.sin(x)}\n" +   // define sin
            "pi = Math.PI\n"                    +    // define pi
            "tan = {double x -> Math.tan(x)}\n" +   // define tan
            "elevarcuadrado  = {double x -> x*x}\n"   +   //define potencia cuadrada
            "elevarcubo  = {double x -> x*x*x}\n"   +   //define potencia cubo
            "sqrt  = {double x -> Math.sqrt(x)}\n"      //define raiz
                  
                  
          );
            res = (double) shell.evaluate(equation);
            listY.add((float)res);  
        }
        return listY;
    }
    
    
        public static float areaRectangular(float a, float b,  List<Float> x, List<Float> y){

        int i = 0;
        float area = 0;
        for(Float f : x){
            if(i == 0){
                area += y.get(i) * (distancia(a, f));
                i++;
            }else{
                area += y.get(i) * (distancia(x.get(i - 1), f));
                //System.out.println( "abs " + y.get(i) * Math.abs(distancia(x.get(i - 1), f)));
                i++;
            }
        }
        return area;
    }
        
    public static float areaTrapezoidal(float a, float b,  List<Float> x, List<Float> y){

        int i = 0;
        float area = 0;
        for(Float f : x){
         
            if(( i + 1) < x.size()){
                area += y.get(i) * distancia(x.get(i), x.get(i + 1));
                area += ((y.get(i + 1) - y.get(i)) * (distancia(x.get(i), x.get(i + 1)))) / 2;
                i++;
            }
           
        }
        return area;
    }
    
    public static float areaSemicircular(float a, float b,  List<Float> x, List<Float> y){

        int i = 0;
        float area = 0;
        float pi = (float)3.1415926;
        int signo = 1;
        for(Float f : x){
            if(i == 0){
                area += y.get(i) * distancia(a, f);
                if(y.get(i) >= 0)
                    signo = 1;
                else signo = -1;
                area += signo * (pi * Math.pow(distancia(a, f), 2));
                i++;
            }else{
                if(y.get(i) >= 0)
                    signo = 1;
                else signo = -1;
                area += y.get(i) * distancia(x.get(i - 1), f);
                area += signo * (pi * Math.abs(Math.pow(distancia(x.get(i - 1), f), 2)));
                i++;
            }
        }
        return area;
    }
    
    public static List<Float>  particionSin(List<Float> x,float a, float b){

        
        List<Float> listY = new ArrayList<>();
        List<Float> listY2 = new ArrayList<>();
        for(Float f : x){
            listY.add((float)Math.sin(f)); 
        }
        for(int i = 0; i < x.size(); i++){
            //System.out.println(listY.get(i) * x.get(i));
            if(listY.get(i) * x.get(i) <= b){
                listY2.add(listY.get(i) * x.get(i)); 
            }
        }
        return listY2;
    }
        public static List<Float>  xMasUno(List<Float> x,float a, float b){

        
        List<Float> listY = new ArrayList<>();
        List<Float> listY2 = new ArrayList<>();
        for(Float f : x){
            listY.add(f + 1); 
        }
        for(int i = 0; i < x.size(); i++){
            if(listY.get(i) * x.get(i) <= b){
                listY2.add(listY.get(i) * x.get(i)); 
            }
        }
        return listY2;
    }
    public static List<Float>  xALa2(List<Float> x,float a, float b){

        
        List<Float> listY = new ArrayList<>();
        List<Float> listY2 = new ArrayList<>();
        for(Float f : x){
            listY.add((float)Math.pow(f,2)); 
        }
        for(int i = 0; i < x.size(); i++){
            if(listY.get(i) * x.get(i) <= b){
                listY2.add(listY.get(i) * x.get(i)); 
            }
        }
        return listY2;
    }
/*
    public static float  derivada1(float a, float b,  List<Float> x, List<Float> y, String equation){

        
        int i = 0;
        float derivada = 0;
        List<Float> listIzq = puntosY(puntosIzq(x),equation);
        List<Float> listDer = puntosY(puntosDer(x), equation);
        
        for(Float f : x){
         
            if(( i + 1) < x.size()){
                if(( i -1 ) >= 0){
                    derivada += (listDer.get(i) - listIzq.get(i)) / (2 * distancia(x.get(i), x.get(i + 1)));
                    
                }
                i++;
            }
           
        }
        return derivada;
    }
*/
    public static List<Float> puntosDer( List<Float> x){
        
        List<Float> listY = new ArrayList<>();
        int i = 0;
        for(Float f : x){
            
            if(( i + 1) < x.size()){
                listY.add(f + distancia(x.get(i),x.get(i+1))); 
                i++;
            }
        }
        return listY;
    }
    public static List<Float> puntosIzq( List<Float> x){
        
        List<Float> listY = new ArrayList<>();
        int i = 0;
        for(Float f : x){
            
            if(( i + 1) < x.size()){
                listY.add(f - distancia(x.get(i),x.get(i+1))); 
                i++;
            }
        }
        return listY;
    }
    /*
        public static float  derivada2(float a, float b,  List<Float> x, List<Float> y, String equation){

        
        int i = 0;
        float derivada2 = 0;
        List<Float> listIzq = puntosY(puntosIzq(x),equation);
        List<Float> listDer = puntosY(puntosDer(x),equation);
        System.out.println("der: " + listDer.size() + "izq: " + listDer.size() + "x: " + x.size() + "y: " + y.size());
        for(Float f : x){
         
            if(( i + 1) < x.size()){
                
                    derivada2 += (listDer.get(i) + listIzq.get(i) - (2 * y.get(i))) / ( Math.pow(distancia(x.get(i), x.get(i + 1)),2));
                    
                
                i++;
            }
           
        }
        return derivada2;
    }
*/
    public static float  errorTruncamientoTrap(float a, float b,  List<Float> x, List<Float> y, String equation){

        
        int i = 0;
        float errorTruncamientoTrap = 0;
        float derivada2 = 0;
        List<Float> listIzq = puntosY(puntosIzq(x),equation);
        List<Float> listDer = puntosY(puntosDer(x),equation);
         System.out.println("der: " + listDer.size() + "izq: " + listDer.size() + "x: " + x.size() + "y: " + y.size());
        for(Float f : x){
         
            if(( i + 1) < x.size()){
                if(( i -1 ) >= 0){
                    derivada2 += (listDer.get(i) + listIzq.get(i) - (2 * y.get(i))) / ( Math.pow(distancia(x.get(i), x.get(i + 1)),2));
                    errorTruncamientoTrap +=  (( Math.pow(distancia(x.get(i), x.get(i + 1)),3))/12) * derivada2 * (-1);
                    
                    
                }
                i++;
            }
           
        }
        return errorTruncamientoTrap;
    }
            
}

            



